layout_spectrum: 0.5089356071652272
typography_spectrum: 0.8671679780946694
color:
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
  brandStrength: 0.10552609674678655
  lightness: 0.9471348106571574
  saturation: 0.8891212377929599
  rhythmicContrast: 0.08673600703265777
opengraph:
  appId: 'https://www.facebook.com/Giffydog/'
author:
  name: Cheryl Gfrerer
  email: giffydog@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e13998b1-f3cc-4586-80f0-0989a288fa2e.png
name: Giffydog
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Visit us on Facebook
    url: 'https://www.facebook.com/Giffydog/'
    type: external
  - name: Check out our blog
    id: aca9e99b-46c7-4d18-a609-c912179c3898
    type: content
title: Giffy dog
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FsLbRMo70FX8%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DsLbRMo70FX8&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FsLbRMo70FX8%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Cheryl Gfrerer
          url: 'https://www.youtube.com/channel/UC_l0xNCpumhBAcRk5SnAquw'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://www.youtube.com/favicon.ico'
        domain: www.youtube.com
      keywords: []
      description: >-
        In this video, Kim learns how to add a new cue "through" to replace the
        "follow" cue when jumping through a hoop. This is a great way to build
        upon the touch cue.
      '@type': VideoObject
      app_links: []
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=sLbRMo70FX8'
      title: Jumping through a hoop
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: BE the cookie!
purpose:
  - type: contact
    url: 'mailto:giffydog@gmail.com'
    label: Contact us
github: true
