layout_spectrum: 0.7283778008638816
typography_spectrum: 0.1816685350369293
color:
  brandColors:
    - '#F6F792'
    - '#333745'
    - '#77C4D3'
    - '#DAEDE2'
    - '#EA2E49'
  brandStrength: 0.45719047787294975
  lightness: 0.9924522355651612
  saturation: 0.6889895622320659
  rhythmicContrast: 0.39429150423652837
opengraph:
  appId: 'https://www.facebook.com/Giffydog/'
author:
  name: Cheryl Gfrerer
  email: giffydog@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e13998b1-f3cc-4586-80f0-0989a288fa2e.png
name: Giffydog
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Visit us on Facebook
    url: 'https://www.facebook.com/Giffydog/'
    type: external
  - name: Check out our blog
    id: aca9e99b-46c7-4d18-a609-c912179c3898
    type: content
title: Giffy dog
content: []
description: BE the cookie!
purpose:
  - type: contact
    url: 'mailto:giffydog@gmail.com'
    label: Contact us
github: true
